[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "http://tharcisse.me/*"
to = "https://tharcisse.me/:splat"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

